[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = {git = "https://github.com/linebender/druid.git" , features =["im"] }
async-std = {version = "1.10.0"}
futures = "0.3.17"
gui = {path = "../gui"}

[[bin]]
name = "kamel"
path = "src/main.rs"